main: org.carlgo11.anti.p12a.Main
name: AntiP12a
version: A0.2
authors: [carlgo11, tryy3]

commands:
  antip12a:
    description: AntiP12a commands!
    usage: /<command> [help|verify|check]
  verify:
    description: To verify that your not a P12a
    usage: /<command> (Random Numbers/Letters)

permissions:
  antip12a.*:
    description: All antip12a perms!
    children:
      antip12a.verify: true
      antip12a.check: true
      antip12a.help: true
      antip12a.ignoreplayer: true